---

- name: Check current directorys 
  shell: |
    ls -la

- name: Copy backend file repo 
  become: true
  copy:
    src: /root/project/backend.tar.gz
    dest: /home/ubuntu/backend.tar.gz

- name: Install Node modules
  shell: |
    cd /home/ubuntu/
    tar xzvf backend.tar.gz
    mv home/circleci/project/backend .
    cd backend
    sudo npm install
    
- name: building node services
  shell: |
    cd /home/ubuntu/backend
    ls -la 
    sudo npm run build

    
- name: starting up PM2
  become: true
  shell: |
    cd /home/ubuntu/backend 
    pm2 start npm --name backend -- start
    pm2 ls

